REM $Id: server.cmd 3191 2016-09-27 14:42:51Z SFB $

SET CLASS_PATH=%RVPF_CONFIG%/service

SET INITIAL_MEMORY=4
SET MAXIMUM_MEMORY=64

SET MAIN_CLASS=org.rvpf.http.HTTPServerActivator

SET CLASS_PATH=%RVPF_CONFIG%/service/local;%RVPF_CONFIG%/service
SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-http.jar

SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.prefix=server
SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.id=Serv

SET LOG_PREFIX=server

SET SERVICE_NAME=RVPFServer
SET SERVICE_DISPLAY_NAME=RVPF Server
SET SERVICE_DESCRIPTION=RVPF Server
SET SERVICE_DEPENDS_ON=TCPIP

REM End.
