REM $Id: alerter.cmd 3191 2016-09-27 14:42:51Z SFB $

CALL "%RVPF_CONFIG%/wrap/common"

SET MAIN_CLASS=org.rvpf.http.HTTPServerActivator

SET PARAMETERS=name=Alerter

SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-http.jar
SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-processor.jar
SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-store.jar

SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.prefix=alerter
SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.id=Aler

SET LOG_PREFIX=alerter

SET SERVICE_NAME=RVPFAlerter
SET SERVICE_DISPLAY_NAME=RVPF Alerter
SET SERVICE_DESCRIPTION=RVPF HTTP Alerter Service
SET SERVICE_DEPENDS_ON=TCPIP

REM End.
