REM $Id: http.cmd 3191 2016-09-27 14:42:51Z SFB $

CALL "%RVPF_CONFIG%/wrap/common"

SET MAIN_CLASS=org.rvpf.http.HTTPServerActivator

SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-http.jar

SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.prefix=http
SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.id=Http

SET LOG_PREFIX=http

SET SERVICE_NAME=RVPFHTTP
SET SERVICE_DISPLAY_NAME=RVPF HTTP
SET SERVICE_DESCRIPTION=RVPF HTTP Service
SET SERVICE_DEPENDS_ON=TCPIP

REM End.
