REM $Id: soms.cmd 3191 2016-09-27 14:42:51Z SFB $

CALL "%RVPF_CONFIG%/wrap/common"

SET MAIN_CLASS=org.rvpf.som.SOMContainerServiceActivator

SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-service.jar

SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.prefix=soms
SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.id=SomS

SET LOG_PREFIX=soms

SET SERVICE_NAME=RVPFSOM
SET SERVICE_DISPLAY_NAME=RVPF SOM
SET SERVICE_DESCRIPTION=RVPF SOM Server
SET SERVICE_DEPENDS_ON=TCPIP

REM End.
