REM $Id: to082.cmd 3191 2016-09-27 14:42:51Z SFB $

CALL "%RVPF_CONFIG%/wrap/common"

SET MAIN_CLASS=org.rvpf.forwarder.ForwarderServiceActivator

SET PARAMETERS=name=To082

SET CLASS_PATH=%CLASS_PATH%;%RVPF_CORE_SHARE_JAVA%/rvpf-forwarder.jar

SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.prefix=to082
SET JVM_OPTIONS=%JVM_OPTIONS%;-Drvpf.log.id=T082

SET LOG_PREFIX=forwarder

SET SERVICE_NAME=RVPFForwarderTo082
SET SERVICE_DISPLAY_NAME=RVPF Forwarder to 082
SET SERVICE_DESCRIPTION=RVPF HTTP Forwarder to 082 Service
SET SERVICE_DEPENDS_ON=TCPIP

REM End.
