# Related Values Processing Framework (JNLP support).
#
# Copyright (C) 2003-2019 Serge Brisson.
#
# This software is distributable under the LGPL license.
# See details at the bottom of this file.
#
# $Id: Makefile 3961 2019-05-06 20:14:59Z SFB $

NAME := jnlp
DEPLOY := 1

include ../core/config/build/Makefile.in

# This is free software; you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License
# version 2.1 as published by the Free Software Foundation.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this software; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
